version: '3.7'

services:
  database:
    container_name: postgres-server
    restart: always
    image: postgres:latest
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social
    networks:
      - friend-management-network

  server:
    container_name: golang-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    depends_on:
      - database
    networks:
      - friend-management-network

volumes:
  dbinit:

networks:
  friend-management-network:
    driver: bridge